### ISSUE TITLE
ModuleNotFoundError: No module named 'jsmin'

### ISSUE THREAD

**Issue by itzyoungen** [tikitu/jsmin#30]
Traceback (most recent call last):
  File "./server.py", line 13, in <module>
    from jsmin import jsmin
ModuleNotFoundError: No module named 'jsmin'

error comes from running a python 3 script.

**Comment by tikitu** [comment]
The CI results shown in the README seem to show that python 3 is supported. I'm afraid I can't investigate your problem without more information, but I would _guess_ that the problem is likely to be related to packaging rather than to `jsmin`. Please also note that this package is more or less unmaintained these days, and does not support modern javascript: it's quite likely that you would be better off using a different tool entirely.

**Comment by itzyoungen** [comment]
well what you did seemed to work. ran apt-get update, removed project folder and contents and re cloned. install succeed no issues.
